import = [
  "~/.config/alacritty/theme/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"

[window.padding]
x = 10
y = 10

[font]
size = 12

[font.normal]
family = "JetBrainsMono Nerd Font"

[cursor]
style = "Block"
